name: mobile
description: Tuturuuu Mobile
version: 0.0.1+2
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.41.0

dependencies:
  bloc: ^9.2.0
  cached_network_image: ^3.4.1
  cloudflare_turnstile: ^3.6.2
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  equatable: ^2.0.8
  firebase_analytics: ^12.1.2
  firebase_crashlytics: ^5.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  go_router: ^17.1.0
  http: ^1.6.0
  http_parser: ^4.1.2
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.10.0
  lucide_icons: ^0.257.0
  mime: ^2.0.0
  package_info_plus: ^9.0.0
  shadcn_flutter: ^0.0.51
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.12.0
  url_launcher: ^6.3.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.11.1
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.12.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
